port: 8080
debug: true

callbackAddress: http://192.168.0.105:8080

mysql:
  user: root
  password: 123456
  address: 192.168.0.109
  port: 3306
  db: eventops

minio:
  server: http://192.168.0.109:9000
  accessKeyId: nf9SdeSrq7R4ffct
  secretAccessKey: fPnttv7iWo5MQytu1IJ6SpK39078ED52
  ssl: false
  basePath: eventops

actuator:
  printTunnelData: true

event:
  process:
    bufferSize: 500
    workNum: 5
    triggerCacheSize: 10000
    loopLoadEventInterval: 300
    processingOverTime: 120

uc:
  loginTokenExpiresTime: 315360000
  loginTokenSignature: MYSQL_SIGNATURE
  auth:
    whiteUrlList:
      - /api/user/register
      - /api/user/login
      - /api/dialer/connect
      - /api/pipeline/callback
